# Generated by Django 4.0.5 on 2022-09-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
