# Generated by Django 4.0.5 on 2022-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_gender_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('consent_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
