# Generated by Django 4.0.5 on 2022-09-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_consent_consent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
