# Generated by Django 4.0.5 on 2022-09-25 08:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userpreference_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
