# Generated by Django 4.0.5 on 2022-09-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatalog',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'Order Status'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
