# Generated by Django 4.0.5 on 2022-09-15 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_productcatalog_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_list_item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='ProductPricelist',
        ),
    ]
