# Generated by Django 4.0.5 on 2022-09-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_paymentmethod_shipping_shopcart_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='owner',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
