# Generated by Django 4.0.5 on 2022-09-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopcart_session_id_alter_shopcart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
