# Generated by Django 4.0.5 on 2022-09-17 07:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='id',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='cart_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopcart',
            name='owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
