# Generated by Django 4.0.5 on 2022-09-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_id_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
