# Generated by Django 4.0.5 on 2022-09-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_payment_price_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
