# Generated by Django 4.0.5 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
