# Generated by Django 4.0.5 on 2022-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_currency_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='used',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
