# Generated by Django 4.0.5 on 2022-09-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_currency_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, null=True),
        ),
    ]
