# Generated by Django 4.0.5 on 2022-09-25 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_orderitem_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
    ]
