# Generated by Django 4.0.5 on 2022-09-28 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Categories'},
        ),
    ]
