# Generated by Django 4.0.5 on 2022-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_productcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='session_id',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='user_id',
            field=models.UUIDField(null=True),
        ),
    ]
