# Generated by Django 4.0.5 on 2022-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_shopcart_session_id_shopcart_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['name'], 'verbose_name_plural': 'Shipping'},
        ),
    ]
