# Generated by Django 4.0.5 on 2022-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_shipping_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
    ]
