# Generated by Django 4.0.5 on 2022-10-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_paymentmethod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Currencies'},
        ),
    ]
